###
POST http://localhost:8080/gateway/mtop/weight/manage/upload
Content-Type: application/json

{
  "body": {
    "weight": 86.9,
    "fileName": "/Users/danggui/Downloads/IMG_734",
    "remoteName": "20240109.JPG",
    "forceUpload": false,
    "dateTime": "2024-01-09"
  }
}
### 健康检查接口
GET http://localhost:8080/ping

### 获取gateway接口列表
GET http://localhost:8080/gateway/mtop/api/list

### applicationList
POST http://localhost:8080/gateway/mtop/gpt/application/list
Content-Type: application/json

{
  "body": {
    "page" : {
      "pageNo" : 1,
      "pageSize" : 10
    }
  }
}

### chat
POST http://localhost:8080/gateway/mtop/gpt/application/chat
Content-Type: application/json

{
  "body": {
    "modelId" : 2,
    "sessionId": "c6d15b75f7e3438e89eda32bd879953f",
    "prompt" : "这是我们的第几次对话"
  }
}
