###
POST http://localhost:8080/gateway/mtop/weight/manage/upload
Content-Type: application/json

{
  "body": {
    "weight": 86.9,
    "fileName": "/Users/danggui/Downloads/IMG_7341.JPG",
    "remoteName": "20240109.JPG",
    "forceUpload": false,
    "dateTime": "2024-01-09"
  }
}
### 健康检查接口
GET http://localhost:8080/ping

### 获取gateway接口列表
GET http://localhost:8080/gateway/mtop/api/list