// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "parent_id", Type: field.TypeInt32},
		{Name: "model", Type: field.TypeString},
		{Name: "is_application", Type: field.TypeBool},
		{Name: "access_key", Type: field.TypeString},
		{Name: "secret_key", Type: field.TypeString},
		{Name: "desc", Type: field.TypeString},
		{Name: "dashboard", Type: field.TypeString},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TenantsTable,
	}
)

func init() {
	TenantsTable.Annotation = &entsql.Annotation{
		Table: "tenants",
	}
}
