// Code generated by hertz generator.

package main

import (
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	"msp/gateway/config"
	"msp/gateway/initialize"
)

func main() {

	// 本地配置文件初始化
	initialize.InitLocalConfig()
	// 根据本地配置文件初始化日志
	initialize.InitLogger()
	// 根据本地配置文件初始化配置
	initialize.InitConfig()
	// 注册中心
	r, info := initialize.InitRegistry(config.GlobalServerConfig.Port)
	tracer, trcCfg := hertztracing.NewServerTracer()

	// create a new server
	h := server.New(
		tracer,
		server.WithALPN(true),
		server.WithHostPorts(fmt.Sprintf(":%d", config.GlobalServerConfig.Port)),
		server.WithRegistry(r, info),
		server.WithHandleMethodNotAllowed(true),
	)
	h.Use(hertztracing.ServerMiddleware(trcCfg))
	register(h)

	routeInfo := h.Routes()
	hlog.Info(routeInfo)
	h.Spin()
}
