// Code generated by Kitex v0.10.1. DO NOT EDIT.

package chatservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	gpt "msp/biz_server/kitex_gen/gpt"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Chat": kitex.NewMethodInfo(
		chatHandler,
		newChatServiceChatArgs,
		newChatServiceChatResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChatApplicationList": kitex.NewMethodInfo(
		chatApplicationListHandler,
		newChatServiceChatApplicationListArgs,
		newChatServiceChatApplicationListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	chatServiceServiceInfo                = NewServiceInfo()
	chatServiceServiceInfoForClient       = NewServiceInfoForClient()
	chatServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return chatServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return chatServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return chatServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ChatService"
	handlerType := (*gpt.ChatService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "gpt",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.10.1",
		Extra:           extra,
	}
	return svcInfo
}

func chatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*gpt.ChatServiceChatArgs)
	realResult := result.(*gpt.ChatServiceChatResult)
	success, err := handler.(gpt.ChatService).Chat(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceChatArgs() interface{} {
	return gpt.NewChatServiceChatArgs()
}

func newChatServiceChatResult() interface{} {
	return gpt.NewChatServiceChatResult()
}

func chatApplicationListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*gpt.ChatServiceChatApplicationListArgs)
	realResult := result.(*gpt.ChatServiceChatApplicationListResult)
	success, err := handler.(gpt.ChatService).ChatApplicationList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceChatApplicationListArgs() interface{} {
	return gpt.NewChatServiceChatApplicationListArgs()
}

func newChatServiceChatApplicationListResult() interface{} {
	return gpt.NewChatServiceChatApplicationListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Chat(ctx context.Context, req *gpt.ApplicationReq) (r *gpt.ApplicationResp, err error) {
	var _args gpt.ChatServiceChatArgs
	_args.Req = req
	var _result gpt.ChatServiceChatResult
	if err = p.c.Call(ctx, "Chat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChatApplicationList(ctx context.Context, req *gpt.ApplicationListReq) (r *gpt.ApplicationListResp, err error) {
	var _args gpt.ChatServiceChatApplicationListArgs
	_args.Req = req
	var _result gpt.ChatServiceChatApplicationListResult
	if err = p.c.Call(ctx, "ChatApplicationList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
