// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"msp/biz_server/gpt/internal/infra/mysql/model/ent/chat"
	"msp/biz_server/gpt/internal/infra/mysql/model/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatUpdate is the builder for updating Chat entities.
type ChatUpdate struct {
	config
	hooks    []Hook
	mutation *ChatMutation
}

// Where appends a list predicates to the ChatUpdate builder.
func (cu *ChatUpdate) Where(ps ...predicate.Chat) *ChatUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *ChatUpdate) SetUpdatedAt(t time.Time) *ChatUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetModelID sets the "model_id" field.
func (cu *ChatUpdate) SetModelID(i int32) *ChatUpdate {
	cu.mutation.ResetModelID()
	cu.mutation.SetModelID(i)
	return cu
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (cu *ChatUpdate) SetNillableModelID(i *int32) *ChatUpdate {
	if i != nil {
		cu.SetModelID(*i)
	}
	return cu
}

// AddModelID adds i to the "model_id" field.
func (cu *ChatUpdate) AddModelID(i int32) *ChatUpdate {
	cu.mutation.AddModelID(i)
	return cu
}

// SetSessionID sets the "session_id" field.
func (cu *ChatUpdate) SetSessionID(s string) *ChatUpdate {
	cu.mutation.SetSessionID(s)
	return cu
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (cu *ChatUpdate) SetNillableSessionID(s *string) *ChatUpdate {
	if s != nil {
		cu.SetSessionID(*s)
	}
	return cu
}

// SetName sets the "name" field.
func (cu *ChatUpdate) SetName(s string) *ChatUpdate {
	cu.mutation.SetName(s)
	return cu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cu *ChatUpdate) SetNillableName(s *string) *ChatUpdate {
	if s != nil {
		cu.SetName(*s)
	}
	return cu
}

// Mutation returns the ChatMutation object of the builder.
func (cu *ChatUpdate) Mutation() *ChatMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChatUpdate) Save(ctx context.Context) (int, error) {
	cu.defaults()
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChatUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChatUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChatUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *ChatUpdate) defaults() {
	if _, ok := cu.mutation.UpdatedAt(); !ok {
		v := chat.UpdateDefaultUpdatedAt()
		cu.mutation.SetUpdatedAt(v)
	}
}

func (cu *ChatUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(chat.Table, chat.Columns, sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt32))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(chat.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cu.mutation.ModelID(); ok {
		_spec.SetField(chat.FieldModelID, field.TypeInt32, value)
	}
	if value, ok := cu.mutation.AddedModelID(); ok {
		_spec.AddField(chat.FieldModelID, field.TypeInt32, value)
	}
	if value, ok := cu.mutation.SessionID(); ok {
		_spec.SetField(chat.FieldSessionID, field.TypeString, value)
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.SetField(chat.FieldName, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ChatUpdateOne is the builder for updating a single Chat entity.
type ChatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *ChatUpdateOne) SetUpdatedAt(t time.Time) *ChatUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetModelID sets the "model_id" field.
func (cuo *ChatUpdateOne) SetModelID(i int32) *ChatUpdateOne {
	cuo.mutation.ResetModelID()
	cuo.mutation.SetModelID(i)
	return cuo
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillableModelID(i *int32) *ChatUpdateOne {
	if i != nil {
		cuo.SetModelID(*i)
	}
	return cuo
}

// AddModelID adds i to the "model_id" field.
func (cuo *ChatUpdateOne) AddModelID(i int32) *ChatUpdateOne {
	cuo.mutation.AddModelID(i)
	return cuo
}

// SetSessionID sets the "session_id" field.
func (cuo *ChatUpdateOne) SetSessionID(s string) *ChatUpdateOne {
	cuo.mutation.SetSessionID(s)
	return cuo
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillableSessionID(s *string) *ChatUpdateOne {
	if s != nil {
		cuo.SetSessionID(*s)
	}
	return cuo
}

// SetName sets the "name" field.
func (cuo *ChatUpdateOne) SetName(s string) *ChatUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillableName(s *string) *ChatUpdateOne {
	if s != nil {
		cuo.SetName(*s)
	}
	return cuo
}

// Mutation returns the ChatMutation object of the builder.
func (cuo *ChatUpdateOne) Mutation() *ChatMutation {
	return cuo.mutation
}

// Where appends a list predicates to the ChatUpdate builder.
func (cuo *ChatUpdateOne) Where(ps ...predicate.Chat) *ChatUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChatUpdateOne) Select(field string, fields ...string) *ChatUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Chat entity.
func (cuo *ChatUpdateOne) Save(ctx context.Context) (*Chat, error) {
	cuo.defaults()
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChatUpdateOne) SaveX(ctx context.Context) *Chat {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChatUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChatUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *ChatUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdatedAt(); !ok {
		v := chat.UpdateDefaultUpdatedAt()
		cuo.mutation.SetUpdatedAt(v)
	}
}

func (cuo *ChatUpdateOne) sqlSave(ctx context.Context) (_node *Chat, err error) {
	_spec := sqlgraph.NewUpdateSpec(chat.Table, chat.Columns, sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt32))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chat.FieldID)
		for _, f := range fields {
			if !chat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(chat.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.ModelID(); ok {
		_spec.SetField(chat.FieldModelID, field.TypeInt32, value)
	}
	if value, ok := cuo.mutation.AddedModelID(); ok {
		_spec.AddField(chat.FieldModelID, field.TypeInt32, value)
	}
	if value, ok := cuo.mutation.SessionID(); ok {
		_spec.SetField(chat.FieldSessionID, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.SetField(chat.FieldName, field.TypeString, value)
	}
	_node = &Chat{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
