// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"msp/biz_server/gpt/internal/infra/mysql/model/ent/predicate"
	"msp/biz_server/gpt/internal/infra/mysql/model/ent/tenant"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantUpdate is the builder for updating Tenant entities.
type TenantUpdate struct {
	config
	hooks    []Hook
	mutation *TenantMutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (tu *TenantUpdate) Where(ps ...predicate.Tenant) *TenantUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TenantUpdate) SetUpdatedAt(t time.Time) *TenantUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetName sets the "name" field.
func (tu *TenantUpdate) SetName(s string) *TenantUpdate {
	tu.mutation.SetName(s)
	return tu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableName(s *string) *TenantUpdate {
	if s != nil {
		tu.SetName(*s)
	}
	return tu
}

// SetParentID sets the "parent_id" field.
func (tu *TenantUpdate) SetParentID(i int32) *TenantUpdate {
	tu.mutation.ResetParentID()
	tu.mutation.SetParentID(i)
	return tu
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableParentID(i *int32) *TenantUpdate {
	if i != nil {
		tu.SetParentID(*i)
	}
	return tu
}

// AddParentID adds i to the "parent_id" field.
func (tu *TenantUpdate) AddParentID(i int32) *TenantUpdate {
	tu.mutation.AddParentID(i)
	return tu
}

// SetModel sets the "model" field.
func (tu *TenantUpdate) SetModel(s string) *TenantUpdate {
	tu.mutation.SetModel(s)
	return tu
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableModel(s *string) *TenantUpdate {
	if s != nil {
		tu.SetModel(*s)
	}
	return tu
}

// SetIsApplication sets the "is_application" field.
func (tu *TenantUpdate) SetIsApplication(b bool) *TenantUpdate {
	tu.mutation.SetIsApplication(b)
	return tu
}

// SetNillableIsApplication sets the "is_application" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableIsApplication(b *bool) *TenantUpdate {
	if b != nil {
		tu.SetIsApplication(*b)
	}
	return tu
}

// SetAccessKey sets the "access_key" field.
func (tu *TenantUpdate) SetAccessKey(s string) *TenantUpdate {
	tu.mutation.SetAccessKey(s)
	return tu
}

// SetNillableAccessKey sets the "access_key" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableAccessKey(s *string) *TenantUpdate {
	if s != nil {
		tu.SetAccessKey(*s)
	}
	return tu
}

// SetSecretKey sets the "secret_key" field.
func (tu *TenantUpdate) SetSecretKey(s string) *TenantUpdate {
	tu.mutation.SetSecretKey(s)
	return tu
}

// SetNillableSecretKey sets the "secret_key" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableSecretKey(s *string) *TenantUpdate {
	if s != nil {
		tu.SetSecretKey(*s)
	}
	return tu
}

// SetDesc sets the "desc" field.
func (tu *TenantUpdate) SetDesc(s string) *TenantUpdate {
	tu.mutation.SetDesc(s)
	return tu
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableDesc(s *string) *TenantUpdate {
	if s != nil {
		tu.SetDesc(*s)
	}
	return tu
}

// SetDashboard sets the "dashboard" field.
func (tu *TenantUpdate) SetDashboard(s string) *TenantUpdate {
	tu.mutation.SetDashboard(s)
	return tu
}

// SetNillableDashboard sets the "dashboard" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableDashboard(s *string) *TenantUpdate {
	if s != nil {
		tu.SetDashboard(*s)
	}
	return tu
}

// Mutation returns the TenantMutation object of the builder.
func (tu *TenantUpdate) Mutation() *TenantMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TenantUpdate) Save(ctx context.Context) (int, error) {
	tu.defaults()
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TenantUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TenantUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TenantUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *TenantUpdate) defaults() {
	if _, ok := tu.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		tu.mutation.SetUpdatedAt(v)
	}
}

func (tu *TenantUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := tu.mutation.ParentID(); ok {
		_spec.SetField(tenant.FieldParentID, field.TypeInt32, value)
	}
	if value, ok := tu.mutation.AddedParentID(); ok {
		_spec.AddField(tenant.FieldParentID, field.TypeInt32, value)
	}
	if value, ok := tu.mutation.Model(); ok {
		_spec.SetField(tenant.FieldModel, field.TypeString, value)
	}
	if value, ok := tu.mutation.IsApplication(); ok {
		_spec.SetField(tenant.FieldIsApplication, field.TypeBool, value)
	}
	if value, ok := tu.mutation.AccessKey(); ok {
		_spec.SetField(tenant.FieldAccessKey, field.TypeString, value)
	}
	if value, ok := tu.mutation.SecretKey(); ok {
		_spec.SetField(tenant.FieldSecretKey, field.TypeString, value)
	}
	if value, ok := tu.mutation.Desc(); ok {
		_spec.SetField(tenant.FieldDesc, field.TypeString, value)
	}
	if value, ok := tu.mutation.Dashboard(); ok {
		_spec.SetField(tenant.FieldDashboard, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TenantUpdateOne is the builder for updating a single Tenant entity.
type TenantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TenantUpdateOne) SetUpdatedAt(t time.Time) *TenantUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetName sets the "name" field.
func (tuo *TenantUpdateOne) SetName(s string) *TenantUpdateOne {
	tuo.mutation.SetName(s)
	return tuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableName(s *string) *TenantUpdateOne {
	if s != nil {
		tuo.SetName(*s)
	}
	return tuo
}

// SetParentID sets the "parent_id" field.
func (tuo *TenantUpdateOne) SetParentID(i int32) *TenantUpdateOne {
	tuo.mutation.ResetParentID()
	tuo.mutation.SetParentID(i)
	return tuo
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableParentID(i *int32) *TenantUpdateOne {
	if i != nil {
		tuo.SetParentID(*i)
	}
	return tuo
}

// AddParentID adds i to the "parent_id" field.
func (tuo *TenantUpdateOne) AddParentID(i int32) *TenantUpdateOne {
	tuo.mutation.AddParentID(i)
	return tuo
}

// SetModel sets the "model" field.
func (tuo *TenantUpdateOne) SetModel(s string) *TenantUpdateOne {
	tuo.mutation.SetModel(s)
	return tuo
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableModel(s *string) *TenantUpdateOne {
	if s != nil {
		tuo.SetModel(*s)
	}
	return tuo
}

// SetIsApplication sets the "is_application" field.
func (tuo *TenantUpdateOne) SetIsApplication(b bool) *TenantUpdateOne {
	tuo.mutation.SetIsApplication(b)
	return tuo
}

// SetNillableIsApplication sets the "is_application" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableIsApplication(b *bool) *TenantUpdateOne {
	if b != nil {
		tuo.SetIsApplication(*b)
	}
	return tuo
}

// SetAccessKey sets the "access_key" field.
func (tuo *TenantUpdateOne) SetAccessKey(s string) *TenantUpdateOne {
	tuo.mutation.SetAccessKey(s)
	return tuo
}

// SetNillableAccessKey sets the "access_key" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableAccessKey(s *string) *TenantUpdateOne {
	if s != nil {
		tuo.SetAccessKey(*s)
	}
	return tuo
}

// SetSecretKey sets the "secret_key" field.
func (tuo *TenantUpdateOne) SetSecretKey(s string) *TenantUpdateOne {
	tuo.mutation.SetSecretKey(s)
	return tuo
}

// SetNillableSecretKey sets the "secret_key" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableSecretKey(s *string) *TenantUpdateOne {
	if s != nil {
		tuo.SetSecretKey(*s)
	}
	return tuo
}

// SetDesc sets the "desc" field.
func (tuo *TenantUpdateOne) SetDesc(s string) *TenantUpdateOne {
	tuo.mutation.SetDesc(s)
	return tuo
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableDesc(s *string) *TenantUpdateOne {
	if s != nil {
		tuo.SetDesc(*s)
	}
	return tuo
}

// SetDashboard sets the "dashboard" field.
func (tuo *TenantUpdateOne) SetDashboard(s string) *TenantUpdateOne {
	tuo.mutation.SetDashboard(s)
	return tuo
}

// SetNillableDashboard sets the "dashboard" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableDashboard(s *string) *TenantUpdateOne {
	if s != nil {
		tuo.SetDashboard(*s)
	}
	return tuo
}

// Mutation returns the TenantMutation object of the builder.
func (tuo *TenantUpdateOne) Mutation() *TenantMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (tuo *TenantUpdateOne) Where(ps ...predicate.Tenant) *TenantUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TenantUpdateOne) Select(field string, fields ...string) *TenantUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Tenant entity.
func (tuo *TenantUpdateOne) Save(ctx context.Context) (*Tenant, error) {
	tuo.defaults()
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TenantUpdateOne) SaveX(ctx context.Context) *Tenant {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TenantUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TenantUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *TenantUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		tuo.mutation.SetUpdatedAt(v)
	}
}

func (tuo *TenantUpdateOne) sqlSave(ctx context.Context) (_node *Tenant, err error) {
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for _, f := range fields {
			if !tenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.ParentID(); ok {
		_spec.SetField(tenant.FieldParentID, field.TypeInt32, value)
	}
	if value, ok := tuo.mutation.AddedParentID(); ok {
		_spec.AddField(tenant.FieldParentID, field.TypeInt32, value)
	}
	if value, ok := tuo.mutation.Model(); ok {
		_spec.SetField(tenant.FieldModel, field.TypeString, value)
	}
	if value, ok := tuo.mutation.IsApplication(); ok {
		_spec.SetField(tenant.FieldIsApplication, field.TypeBool, value)
	}
	if value, ok := tuo.mutation.AccessKey(); ok {
		_spec.SetField(tenant.FieldAccessKey, field.TypeString, value)
	}
	if value, ok := tuo.mutation.SecretKey(); ok {
		_spec.SetField(tenant.FieldSecretKey, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Desc(); ok {
		_spec.SetField(tenant.FieldDesc, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Dashboard(); ok {
		_spec.SetField(tenant.FieldDashboard, field.TypeString, value)
	}
	_node = &Tenant{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
