// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chat is the predicate function for chat builders.
type Chat func(*sql.Selector)

// ChatMessage is the predicate function for chatmessage builders.
type ChatMessage func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)
